config/routes.rb
Rails.application.routes.draw do
  root to: 'catalogs#index'
  get '/signup', to: 'users#new', as: 'signup'

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'

  resources :authors
  resources :publishers
  resources :books
  resources :users, only: [:index, :show, :new, :create]
  resource :session
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :publications, dependent: :destroy
  has_many :books, through: :publications

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    first_name + ' ' + last_name
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_many :publications, dependent: :destroy
  has_many :authors, through: :publications
  validates :title, presence:true
  validates :isbn, presence:true
  validates :description, presence:true
  validates :title, presence:true
  validates :published_at, presence:true
  validates :publisher_id, presence:true
  validates :page_count, numericality:{only_integer: true, greater_than: 0}
  validates :price, numericality:{greater_than_or_equal_to: 0.0}

  mount_uploader :book_cover, BookCoverUploader

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  has_many :publications
  belongs_to :author
  belongs_to :book

  validates :name, presence: true
  validates :name, uniqueness: {case_sensitive: false}




end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
  format: { with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i }
  def full_name
    "#{first_name} #{last_name}"
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def require_signin
    unless current_user
      flash[:danger] = 'Please sign in first!'
      session[:intended_destination] = request.fullpath
      redirect_to signin_path
    end
  end

  def require_admin
    unless current_user.admin?
      flash[:danger] = 'You have to be an admin to do that!'
      redirect_to root_path
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :set_author, except: [:index, :new, :create]

  def index
    @authors = Author.all
  end

  def show
    # require 'pry'; binding.pry
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = 'Author has been created'
      redirect_to @author
    else
      flash.now[:danger] = 'Author has not been created'

      render :new
    end
  end

  def edit; end

  def update
    if @author.update(author_params)
      flash[:success] = 'Author has been updated'
      redirect_to @author
    else
      flash.now[:danger] = 'Author has not been updated'
      render :edit
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = 'Author has been deleted'
      redirect_to authors_path
    end
    # require 'pry'; binding.pry
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end

  def set_author
    @author = Author.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :set_book, except: [:index,:new,:create]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = "Book has been created"
      redirect_to @book
    else
      flash.now[:danger] = "Book has not been created"
      @publishers = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes(book_params)
      flash[:success] = "Book has been updated"
      redirect_to @book
    else
      flash.now[:danger] = "Book has not been updated"
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = "Book has been deleted"
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :book_cover, :price, :isbn, :page_count, :description, :published_at, :publisher_id, author_ids: [])
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

  before_action :set_publisher, except: [:index, :new, :create]

  def index
  end

  def show
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:success] = "A publisher was created"
      redirect_to @publisher
    else
      flash.now[:danger] = "Publisher was not created."
      render :new
    end
  end

  def edit
  end

  def update

    if @publisher.update(publisher_params)
      flash[:success] = "Publisher has been updated"
      redirect_to @publisher
    else
      flash["danger"] = "Publisher was not updated"
      render :edit
    end
  end

  def destroy
    @publisher.destroy
    flash[:success] = "Publisher destroyed"
    redirect_to publishers_path
  end


  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if current_user
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:success] = "Sign in successful"
      if session[:intended_destination]
        redirect_to session[:intended_destination]
        session[:intended_destination] = nil
      else
        redirect_to root_path
      end
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    unless !session[:user_id]
      session[:user_id] = nil
      flash[:success] = "You have been signed out"
    end
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User has been created'
      redirect_to @user
    else
      flash.now[:danger] = 'User has not been created'

      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/authors/_form.html.erb
<%= bootstrap_form_for(@author, :html => {class: 'form-horizontal'}) do |f| %>

  <div class='form-group'>
    <label for='first_name' class='control-label col-md-3'>First Name</label>
    <div class='col-md-9'>
      <%= f.text_field :first_name, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label for='last_name' class='control-label col-md-3'>Last Name</label>
    <div class='col-md-9'>
      <%= f.text_field :last_name, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group actions control-group'>
    <div class='col-md-offset-3'>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/authors/edit.html.erb
<div class="row">
  <h3 class="text-center titles">Edit Author</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/authors/index.html.erb
<%= link_to "Add New Author", new_author_path %>
<ul>
  <% @authors.each do |author| %>
    <li><%= author.first_name + " " + author.last_name %></li>
  <% end %>
</ul>

app/views/authors/new.html.erb
<div class="row">
  <h3 class="text-center titles">Add New Author</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/books/_form.html.erb
<%= bootstrap_form_for(@book, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Title</label>
    <div class='col-sm-9'>
      <%= f.text_field :title, class: 'form-control', hide_label: true, placeholder: 'Title of the book', autofocus: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Isbn</label>
    <div class='col-sm-9'>
      <%= f.text_field :isbn, class: 'form-control', hide_label: true, placeholder: 'Book ISBN' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Page count</label>
    <div class='col-sm-9'>
      <%= f.text_field :page_count, class: 'form-control', hide_label: true, placeholder: 'Number of pages' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Price</label>
    <div class='col-sm-9'>
      <%= f.text_field :price, class: 'form-control', hide_label: true, placeholder: 'Book unit price' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Description</label>
    <div class='col-sm-9'>
      <%= f.text_area :description, class: 'form-control', hide_label: true, placeholder: 'Book description' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Publication date</label>
    <div class='col-sm-9'>
      <%= f.text_field :published_at, placeholder: 'Date format: yyyy-mm-dd', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Publisher</label>
    <div class='col-sm-9'>
      <%= f.select :publisher_id, @publishers.map { |p| [p.name, p.id] },
                      prompt: 'Select a publisher', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Book cover</label>
    <div class='col-sm-9'>
      <%= f.file_field :book_cover, placeholder: 'Book cover', class: 'form-control', hide_label: true %>
    </div>
  </div>


  <div class='form-group'>
    <label class='control-label col-sm-3'>Authors</label>
    <div class='col-sm-9'>
      <%= f.collection_check_boxes :author_ids, @authors, :id, :full_name, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <%# end %>
  <div class='form-group actions control-group'>
    <div class='col-sm-offset-3'>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/books/index.html.erb
<%= link_to "Add New Book", new_book_path %>

app/views/books/new.html.erb
<div class="row">
  <h3 class="text-center titles">Add New Book</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/catalogs/index.html.erb
<h1>Catalog Index Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookstoreApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header' %>

<%= render 'shared/main' %>

<%= render 'shared/footer' %>

</body>
</html>

app/views/shared/_footer.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-10 col-md-offset-1'>
      <footer role="contentinfo">
        <p class="text-center"><small>Copyright &copy; Emmanuel Asante</small></p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
    <nav role="navigation" class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Bookstore App", "#", class: "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><%= link_to "Home", root_path %></li>
                    <li class="active"><%= link_to "Authors", authors_path %></li>
                    <li class="active"><%= link_to "Books", books_path %></li>
                    <li class="active"><%= link_to "Users", users_path %></li>
                    <% unless current_user %>
                    <li class="active"><%= link_to "Sign up", new_user_path %></li>
                    <li class="active"><%= link_to "Sign in", signin_path %></li>
                <% else %>
                    <li class="active"><%= link_to "Sign out", session_path, method: :delete %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/shared/_main.html.erb
<main role="main">
  <div class='container'>
    <%= render 'shared/messages' %>
    <div class='row'>

      <div class='col-md-9'>
        <% if content_for?(:sidebar) %>
          <div class='col-md-3'>
            <%= yield :sidebar %>
          </div>
          <div class='col-md-9'>
            <%= yield %>
          </div>
        <% else %>
          <div class='col-md-10 col-md-offset-1'>
            <%= yield %>
          </div>
        <% end %>
      </div>

      <div class='col-md-3'>
        <div id="cart">
        </div>
      </div>

    </div>
  </div>
</main>

app/views/shared/_messages.html.erb
<% flash.each do |name,msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href="#" class="close" data-dismiss='alert'>&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= link_to user.email, user %><br>
<% end %>

app/views/users/new.html.erb
<%= bootstrap_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <div class='form-group'>
    <label class="control-label col-sm-3">First name</label>
    <div class='col-sm-9'>
      <%= f.text_field :first_name, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class="control-label col-sm-3">Last name</label>
    <div class='col-sm-9'>
      <%= f.text_field :last_name, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class="control-label col-sm-3">Email</label>
    <div class='col-sm-9'>
      <%= f.email_field :email, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class="control-label col-sm-3">Password</label>
    <div class='col-sm-9'>
      <%= f.password_field :password, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label for='user_password_confirmation' class="control-label col-sm-3">Confirmation</label>
    <div class='col-sm-9'>
      <%= f.password_field :password_confirmation, class: 'form-control', hide_label: true %>
    </div>
  </div>
  <hr>

  <%= f.fields_for :addresses do |address| %>
    <div class='form-group'>
      <label for="address_line1" class="control-label col-sm-3">Address</label>
      <div class='col-sm-9'>
        <%= address.text_field :address_line1, class: 'form-control',id: 'address_line1', hide_label: true %>
      </div>
    </div>

    <div class='form-group'>
      <label for="address_line2" class="control-label col-sm-3"></label>
      <div class='col-sm-9'>
        <%= address.text_field :address_line2, class: 'form-control',id: 'address_line2', hide_label: true %>
      </div>
    </div>

    <div class='form-group'>
      <label class="control-label col-sm-3">City</label>
      <div class='col-sm-9'>
        <%= address.text_field :city, class: 'form-control', hide_label: true %>
      </div>
    </div>

    <div class='form-group'>
      <label for="zipcode" class="control-label col-sm-3">Postal Code</label>
      <div class='col-sm-9'>
        <%= address.text_field :zipcode, class: 'form-control',id: 'zipcode', hide_label: true %>
      </div>
    </div>
  <% end %>

  <div class='form-group actions control-group'>
    <div class='col-sm-offset-3'>
      <%= f.submit class:'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<section>
    <div class='col-sm-10 col-sm-offset-1'>
        <header>
            <h3 class='titles'><%= "#{@user.full_name}" %>'s Profile</h3>
        </header>
        <p id="first-name">First name:
            <%= @user.first_name %></p>
        <p id="last-name">Last name:
            <%= @user.last_name %></p>
        <p id="email">Email:
            <%= @user.email %></p>
    </div>
</section>